### PR TITLE
feat(favorite-word): filter stopwords

### PR DESCRIPTION
**Pull request by qoomon**
improves #45

### CODE REVIEW

**Comment by qoomon** [comment]
Anything missing?

**Comment by antonmedv** [comment]
This branch has conflicts that must be resolved

**Comment by qoomon** [comment]
Done.

**Comment by qoomon** [comment]
done

**Comment by qoomon** [comment]
The tests are failing because som test still expect the former badge header

**Comment by antongolub** [comment]
Hey, @qoomon 

Your commit was finally landed in #83

**Pull request closed without merging**
