### PR TITLE
Revert "Delorean badge rework"

### PR DESCRIPTION
**Pull request by antonmedv**
Reverts my-badges/my-badges#57

### CODE REVIEW

**Comment by andrewjswan** [comment]
In dark - not visible

image

**Comment by antonmedv** [comment]
Yes! Im working on a new one.

**Comment by andrewjswan** [comment]
No approximate time?

**Comment by antonmedv** [comment]
From 1w till ....

**Comment by andrewjswan** [comment]
> From 1w till ....

Bad news :)

**Comment by andrewjswan** [comment]
> From 1w till ....

Maybe return the one that was there for now?

**Pull request merged**
