### PR TITLE
Add: Cosmetic commit badge

### PR DESCRIPTION
**Pull request by andrewjswan**

### CODE REVIEW

**Comment by antongolub** [comment]
_Codestyler badge_

How about capturing  `style:` or `lint:`-prefixed commits too? And attach classic `minor code <smth>`?

**Comment by andrewjswan** [comment]
I don’t mind, but I don’t know ts and how to do it beautifully either.  Can you give me some advice?  or maybe add it later, after merge.

**Comment by andrewjswan** [comment]
> How about capturing `style:` or `lint:`-prefixed commits too?

Added https://github.com/my-badges/my-badges/pull/60/files#diff-90732ba42919fd752823a5ff12863dfb760ebf87e256359d3fa143a2da3af85cR14

**Comment by andrewjswan** [comment]
Thanks! 
But something needs to be done with the picture, it doesn’t fit next to the others, especially when it’s reduced.
But I'm not good at pictures, maybe someone has better ideas?

**Comment by antonmedv** [comment]
ChatGPT!

**Comment by antonmedv** [comment]
Go to https://chat.openai.com and ask:
```
Create a badge for XXX. White background. Make it awesome!
```

**Comment by andrewjswan** [comment]
Received so far: not available in your country.

**Comment by antonmedv** [comment]
VPN?

**Pull request merged**
